---
# tasks file for cpm_hardening

- name: Create user.ini file
  win_file:
    path: "C:\\Program Files (x86)\\CyberArk\\Password Manager\\Vault\\user.ini" #TODO replace path with external variables
    state: touch

- name: run CPM hardening
  win_shell: |
    $ErrorActionPreference = "SilentlyContinue"
    $Action = .\CPM_Hardening.ps1
    $Action | Out-File -FilePath "C:\CyberArk\Ansible\cpm_hardening_result.txt"
    $Result = Get-Content "C:\CyberArk\Ansible\cpm_hardening_result.txt" | ConvertFrom-Json
    if ($Result.isSucceeded -eq 2) {
        exit 1
    } else {
        exit 0
    }
  args:
    chdir: "C:\\CyberArk\\Ansible\\CPM\\Central Policy Manager\\InstallationAutomation" #TODO
