---
# tasks file for cpm_hardening

- name: Create user.ini file
  win_file:
    path: "{{ cpm_installation_path }}\\Vault\\user.ini"
    state: touch

- name: run CPM hardening
  win_shell: |
    $ErrorActionPreference = "SilentlyContinue"
    $Action = .\CPM_Hardening.ps1
    $Action | Out-File -FilePath "{{ cpm_installationautomation_folder }}\cpm_hardening_result.txt"
    $Result = Get-Content "{{ cpm_installationautomation_folder }}\cpm_hardening_result.txt" | ConvertFrom-Json
    if ($Result.isSucceeded -eq 2) {
        exit 1
    } else {
        exit 0
    }
  args:
    chdir: "{{ cpm_installationautomation_folder }}"
